// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CarbonBlockStorage: typeof import('~icons/carbon/block-storage')['default']
    CarbonRainDrop: typeof import('~icons/carbon/rain-drop')['default']
    CarbonWebhook: typeof import('~icons/carbon/webhook')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    EpClose: typeof import('~icons/ep/close')['default']
    EpExpand: typeof import('~icons/ep/expand')['default']
    EpFold: typeof import('~icons/ep/fold')['default']
    EpLocation: typeof import('~icons/ep/location')['default']
    Header: typeof import('./src/components/common/Header.vue')['default']
    HeaderBtnItem: typeof import('./src/components/common/headerBtnItem.vue')['default']
    NavTab: typeof import('./src/components/common/NavTab.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/common/Sidebar.vue')['default']
  }
}
